### ISSUE TITLE
app.software.com loads without nothing on the page. (musictime and codetime)

### ISSUE THREAD

**Issue by cal3432** [swdotcom/swdc-vscode-musictime#10]
**Describe the bug**
Nothing loads on app.software.com/ using code-time and app.software.com/music
Oauth for platforms work though.
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Go to 'CodeTime => Menu'
2. Click on 'See advanced metrics'
3. See literally nothing on the webpage. Only trackers, css and scripts loaded.
(why facebook trackers?)

**Expected behavior**
Atleast some metricts like it says on the extension readme.

**ACTUAL RESULTS**
Nothing loaded, here is the html files:

`https://app.software.com/`
https://gist.github.com/cal3432/a66705fd588e0ed20554add4a22e2fa2#file-html

`https://app.software.com/?token`
https://gist.github.com/cal3432/a66705fd588e0ed20554add4a22e2fa2#file-token-html

`https://app.software.com/music`
https://gist.github.com/cal3432/a66705fd588e0ed20554add4a22e2fa2#file-music-html

**Screenshots**
Every page 
![image](https://user-images.githubusercontent.com/57721560/83946523-4db37500-a809-11ea-913c-7ad8a7066d7e.png)

*Specs:**
 - OS: Windows 10 LTS
 - Plugin version: CodeTime 2.2.7 and Music Time For Spotify 2.0.3

**Comment by xavluiz** [comment]
We have identified the issue and will provide a fix for this momentarily. Thank you for the update and we apologize for the inconvenience.
