### ISSUE TITLE
No media controls VScode Windows.

### ISSUE THREAD

**Issue by pedro-garrido** [swdotcom/swdc-vscode-musictime#107]
**Describe the bug**

No buttons to control media in bottom bar of vscode running on windows 10. with Spotify premium account.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Open vscode.
2. play a song with extension menu.

**Expected behavior**

Get a media control on bottom bar.

**ACTUAL RESULTS**

Get a MusicTime label on bottom bar.

**Screenshots**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/92741841/182002088-ec9c5713-d30c-44fb-993e-9963724a0756.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version Music Time for vs-code v2.2.39

**Comment by pedro-garrido** [comment]
Actually its fix downgrading to version 2.2.36

**Comment by m-shumilov** [comment]
It's the same on Linux

**Comment by pedro-garrido** [comment]
This is fixed in last release
