### ISSUE TITLE
Song title not displayed in status bar at bottom (WSL and Windows).

### ISSUE THREAD

**Issue by ScriptingDad** [swdotcom/swdc-vscode-musictime#11]
**Describe the bug**

Connect to device and start playing music.  I'm unable to see the name of the song that is playing.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
1. Ensure device is selected (Click on Listening on device)
1. Start playing a song by clicking on a playlist or just hitting play in the status bar.
1. Wait indefinitely for the song title to be shown.
1. no error to speak of.

**Expected behavior**
```paste below
Expect the title to be shown after a delay in the status bar.
```

**ACTUAL RESULTS**
Status bar often doesn't reflect play status at all. (Play icon doesn't switch to Stop icon and no song title)

**Screenshots**
![image](https://user-images.githubusercontent.com/919859/84055460-dd306380-a982-11ea-81b5-08ecba3dfcb3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (10.0.17134)
 - Plugin version Music Time (2.0.3)

**Additional context**
```paste below
I switch between WSL1 and Windows[Powershell] and figure this might be a problem.
```

**Also, this is the best music playing app that I've so far used.  Thanks and keep it up.**

**Comment by Paulj1989** [comment]
I'm having similar issues, though my OS is Kubuntu 19.10. The music is playing fine, but not seeing the track title.

And I'll echo the thank you and keep up the good work. This is a small issue for an otherwise excellent extension!

**Comment by ScriptingDad** [comment]
And it just randomly started working about 20 minutes ago.

**Comment by ScriptingDad** [comment]
Confirmed it's working not after the 2.0.6 update on Friday so I'm going to close this issue.
