### ISSUE TITLE
No music controls on windows 10

### ISSUE THREAD

**Issue by buttercubz** [swdotcom/swdc-vscode-musictime#12]
when i install it and login on my account the extension no show music controls.

![bug](https://i.ibb.co/dBjpGKS/Capture.jpg)

 - OS: **windows 10 1809**
 - Music Time for Spotify:  **v2.0.5**
 - vscode: **v1.46**

**Comment by xavluiz** [comment]
Thank you for the issue update. We'll look into this now and apologize for the inconvenience.

**Comment by xavluiz** [comment]
Sorry for the delay in getting back to you. The player controls should now display on windows vscode for version 2.0.6. Thank you for your patience.
