### ISSUE TITLE
No Media Control in VSCode

### ISSUE THREAD

**Issue by ShubhamVerma1811** [swdotcom/swdc-vscode-musictime#13]
**Describe the bug**
```paste below
Media Control are not show in the status bar of VSCode
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Open VSCode
2. Connect Music Time to Spotify
3. Check Status Bar for Media Controls

**Expected behaviour
```paste below
Expected to see Media Control i.e Play, Pause etc.. buttons
```

**ACTUAL RESULTS**

```paste below
There is no Media Control shown in status bar
```

**Screenshots**
See at the bottom left for Media Controls.
![Screenshot (20)](https://user-images.githubusercontent.com/25576658/84561800-13982500-ad6d-11ea-94b0-5ab0f7a85f25.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version [e.g. Music Time v2.0.6]

**Additional context**
```paste below
Also, Can't Play songs from the Activity Bar.
```

**Comment by xavluiz** [comment]
Thank you for the issue request. Have you tried selecting a song from one of your playlists to initiate playing a song? Or do you already have your Spotify desktop or web player playing a track? Either case should enable the player controls. If the player controls do not display in either of those cases that would help us understand more about the issue. We can also ensure the player control is visible at all times and a click of the play button will look to start the last played track if a Spotify player is not currently active. Thank you.

**Comment by ShubhamVerma1811** [comment]
I tried:
- Clicking on the song from the playlist
- Tried "Play" option from the command palette
- When Spotify is closed, it prompts for web or desktop player even after opening it Song doesn't play. Also clicking on Open Desktop Player opens Web Player 🤷‍♂️
- Tried when No song was played

Tried all the above ways, didn't work and there was no media control displayed.

**Comment by xavluiz** [comment]
Thank you for the details. I pushed a new version to allow the controls to be visible before a track plays in version 2.0.7. I will also look at the details you've provided to investigate why the song doesn't play after selecting it. Thank you and I apologize for the inconvenience.

**Comment by ShubhamVerma1811** [comment]
After the recent update, media control is visible but still nothing plays and the controls don't work.

**Comment by xavluiz** [comment]
Are you using a Spotify premium or non-premium account? This will also help me understand more. Thanks.

**Comment by ShubhamVerma1811** [comment]
Spotify Free.

**Comment by xavluiz** [comment]
I see, thank you. I'm testing with that kind of account now and will get back to you soon. Thanks again.

**Comment by xavluiz** [comment]
Hi. Unfortunately Spotify does not allow playback via their APIs for non-premium accounts. Liking a song and other non playback functionality is available. I've also fixed an issue that prevented the Spotify error from showing in as a vscode prompt. This message will now be available in v2.0.8.

**Comment by ShubhamVerma1811** [comment]
Oh wow
That's sad :(
Thanks for your efforts to getting this know.

**Comment by xavluiz** [comment]
You're welcome and I apologize the limitation.
