### ISSUE TITLE
Playlist folders not available in playlists list.

### ISSUE THREAD

**Issue by AnalogCyan** [swdotcom/swdc-vscode-musictime#14]
**Describe the bug**
```paste below
The playlists list does not show any playlist folders the user has, and instead just shows all playlists regardless of how they're organized.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Have playlist folders on Spotify.
2. Go to the Music Time 'My Playlists' list in VSC.
3. See lack of playlist folders.

**Expected behavior**
```paste below
User's playlist folders are visible, with playlists organized appropriately.
```

**ACTUAL RESULTS**

```paste below
User's playlist folders are not available, instead just showing the playlists alongside the rest of the user's playlists.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version: Music Time v2.0.9

**Additional context**
```paste below
Playlist folders is a lesser-known feature of Spotify, so I'm not even sure if this is possible info to get and display in these types of contexts, but figured it wouldn't hurt to bring up in the off-chance it is possible.
```

**Comment by yottamo** [comment]
Thank you for the update on this and we apologize, but playlist folder visibility in the plugin is currently not supported as Spotify does not have an open API to provide this functionality. Spotify's developer guidelines currently states "Folders are not returned through the Web API, nor can be created using it". I will ask the team to update the README in regards to this limitation. Thank you.
