### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rcoundon** [swdotcom/swdc-vscode-musictime#18]
- Issue Type: `Performance`
- Extension Name: `music-time`
- Extension Version: `2.0.13`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.47.2`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[softwaredotcom.music-time-unresponsive.cpuprofile.txt](https://github.com/swdotcom/swdc-vscode-musictime/files/4964736/softwaredotcom.music-time-unresponsive.cpuprofile.txt)

**Comment by xavluiz** [comment]
We apologize for the late reply and thank you very much for the issue details. We're optimizing the next release and will bundle it with your suggestion of using webpack. We will release the optimized version within the next week.

regards.

**Comment by xavluiz** [comment]
We've just published v2.0.16 to the marketplace with the webpack bundling update, along with a couple of other code optimizations. Thank you for the suggestion and we will continue to work to improve the plugin.
