### ISSUE TITLE
Reconnect to spotify encounters a 403 at api.software.com.

### ISSUE THREAD

**Issue by ScriptingDad** [swdotcom/swdc-vscode-musictime#20]
**Describe the bug**
```paste below
When prompted to re-connect Spotify I get redirected to https://api.software.com with a JWT Token and get a 403 error. 
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Install addon.
2. Attempt to connect to Spotify.

**Expected behavior**
```paste below
To be redirected to Spotify to provide permissions. 
```

**ACTUAL RESULTS**

```paste below
Error 403 from api.software.com. 
```

**Screenshots**
![image](https://user-images.githubusercontent.com/919859/91075796-990d4080-e60c-11ea-9018-f67adde1543a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0.17134
 - Plugin version: 2.0.16

**Comment by xavluiz** [comment]
We sincerely apologize for the late reply. Is this still happening? We're currently unable to reproduce this at this time. We've upgraded our infrastructure since then and this should be working now, but if not we'll look into this immediately.

Regards.
