### ISSUE TITLE
The delete account button doesn't work

### ISSUE THREAD

**Issue by xdeoxyz** [swdotcom/swdc-vscode-musictime#28]
It doesn't work? I can't delete my account.

**Screenshots**
![image](https://user-images.githubusercontent.com/30370288/97108803-6661f000-1702-11eb-9e07-c292d9564a71.png)

**Comment by mmclead** [comment]
Hi @xdeoxyz I just tested this in our staging environment and it worked correctly.   

I realize it's been a few months, but are you still having this issue?  We take data privacy and control pretty seriously so I'm happy to help anyway I can.
