### ISSUE TITLE
Media controls, shuffle and repeat

### ISSUE THREAD

**Issue by Akapa97** [swdotcom/swdc-vscode-musictime#31]
##### SUMMARY

```paste below
Add media controls to shuffle playlist and repeat songs.
```

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

```paste below
Currently only previous, play/stop and next are available
```
![image](https://user-images.githubusercontent.com/22882537/98830197-083b4980-2432-11eb-9d7c-b38690839646.png)

```paste below
There should be these two additional media controls: 
```
![image](https://user-images.githubusercontent.com/22882537/98830863-cb238700-2432-11eb-90a6-cdaf31b9f650.png)

**Comment by xavluiz** [comment]
this is available in the top title section of the player. here's a screenshot, thank you.
![Screen Shot 2021-03-16 at 8 14 08 AM](https://user-images.githubusercontent.com/35306917/111333178-ab45df00-862f-11eb-8af8-03e62d5c58cd.png)
