### ISSUE TITLE
Metrics not collected

### ISSUE THREAD

**Issue by ajpatterson7** [swdotcom/swdc-vscode-musictime#32]
**Describe the bug**
Both in-app dashboard and web metrics show no data after a few hours of listening + coding.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
1. Install 'Music Time' extension
2. Click on Music Time section in Activity Bar
3. Click 'Open Dashboard'
4. See Personal Top 40 section empty.
5. Click 'See web analytics', then 'Explore Metrics'
6. See 'No data to display.' message.
7. Click any music link in the recommendations or playlists.
8. See no change in data shown in step 4 or 6 after reload.

VSCode Extension List
```
alefragnani.Bookmarks
Arjun.swagger-viewer
chef-software.chef
CoenraadS.bracket-pair-colorizer
DevonDCarew.bazel-code
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
hashicorp.terraform
jebbs.plantuml
jmrog.vscode-nuget-package-manager
ms-azuretools.vscode-azurefunctions
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-python.python
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-wsl
ms-vscode.azure-account
ms-vscode.powershell
ms-vscode.powershell-preview
msazurermtools.azurerm-vscode-tools
PKief.material-icon-theme
rebornix.ruby
redhat.vscode-yaml
shardulm94.trailing-spaces
softwaredotcom.music-time
softwaredotcom.swdc-vscode
tinkertrain.theme-panda
wayou.vscode-todo-highlight
wingrunr21.vscode-ruby
```

**Expected behavior**
Metrics and recommendations to update over time.

**ACTUAL RESULTS**
No new metrics or data collected.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18363
 - Plugin version: Music Time 2.0.22 (Code Time 2.3.18)

**Comment by xavluiz** [comment]
Thank you for the issue update. We'll look at this issue right away.
Regards.

**Comment by xavluiz** [comment]
We will have a fix to show the dashboard tracks and recommendations after our review process. It should be available by tomorrow.
Regards.

**Comment by ajpatterson7** [comment]
This seems to be fixed in that I can view results. I presume over time I'll see changes in playlist. Thanks for the quick response!

**Comment by brettmstevens7** [comment]
Yup! We just finished updating all of our views to use our new data pipeline. It should refresh every week. Let us know if you see any other issues.
