### ISSUE TITLE
Error when attempting to authorize with Spotify on a Mac

### ISSUE THREAD

**Issue by VortrusDev** [swdotcom/swdc-vscode-musictime#34]
**Describe the bug**
```paste below
When you click on "Connect to Spotify", it brings up the webpage asking you to authorize with Spotify (I was logged in already). However, when I click Agree, I get "Oops! Something went wrong, please try again or check out our help area." There is also an object passed in to a console error: {"error":"errorCSRF"}
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Click "Connect to Spotify"
2. Go to Safari and click on Agree (while signed in).
3. See error

**Expected behavior**
```paste below
I expected to be able to authorize the application (as I have done on Windows already - I used it extensively on that platform with no issues).
```

**ACTUAL RESULTS**

```paste below
I was unable to authorize with Spotify, and thus unable to use the extension. 
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Latest release

**Additional context**
```paste below
I am on a MacBook Pro 12, 1 running macOS 10.14.2 (18C54) and Darwin 18.2.0.
```

**Comment by xavluiz** [comment]
We apologize for the late response, but is this still happening?  There are many updates to the plugin in regards to efficiency and bug fixes. We'll look at this right away if so, thank you.

**Comment by Kapcash** [comment]
I just tested, it looks like it has been fixed!

**Comment by VortrusDev** [comment]
Can confirm! It has been fixed!
