### ISSUE TITLE
Search for songs

### ISSUE THREAD

**Issue by mathwro** [swdotcom/swdc-vscode-musictime#4]
##### SUMMARY

```paste below
Would like to be able to search after songs.
```

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

Would completely remove the need to go outside of the editor to control my music

```paste below
Search for songs, show possible results in the pop up menu
```

**Comment by brettmstevens7** [comment]
@mathwro, are you requesting a global search for any song, or a search for songs that are already in your playlists?

**Comment by mathwro** [comment]
@brettmstevens7 I would like a global search

**Comment by brettmstevens7** [comment]
@mathwro your wish is our command! 

![search](https://user-images.githubusercontent.com/27828739/77679921-76d5a080-6f50-11ea-8c9e-94951c4dd507.png)

![search-bar](https://user-images.githubusercontent.com/27828739/77679932-79d09100-6f50-11ea-925c-b8be0d1f2382.png)

![top-results](https://user-images.githubusercontent.com/27828739/77679939-7c32eb00-6f50-11ea-9012-a91a70b6f728.png)

**Comment by mathwro** [comment]
Amazing, much appreciated!
