### ISSUE TITLE
Clicking music title in status bar triggers media stop after a few seconds

### ISSUE THREAD

**Issue by Kapcash** [swdotcom/swdc-vscode-musictime#5]
When I click on the title preview in the status bar, it successfully focus my Spotify window, but then it always triggers a media stop event that causes the player to stop. There is a few seconds of delay between the click and the stop.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Play music on Spotify
2. On vscode, click on the playing music title in the status bar (see screenshot)

<img width="434" alt="Screenshot 2020-04-23 at 18 01 07" src="https://user-images.githubusercontent.com/10612835/80121608-d09bab80-858c-11ea-895e-3e7865157218.png">

3. Wait for the music to stop automatically without any user interaction.

**Expected behavior**

The music should not stop.

**ACTUAL RESULTS**
The spotify player stops the music.

**Desktop (please complete the following information):**
 - OS: macOS (Catalina 10.15.4)
 - Plugin version: 1.8.13

**Comment by xavluiz** [comment]
Thank you for the update on this issue and I apologize for the inconvenience. I've fixed this in version 1.8.14. Thanks again. :)

**Comment by Kapcash** [comment]
You're welcome. I didn't expect such reactivity !
It works well in 1.8.14, thank you so much :)
