### ISSUE TITLE
Extension Kind

### ISSUE THREAD

**Issue by KROSF** [swdotcom/swdc-vscode-musictime#6]
**Describe the bug**

Related to swdotcom/swdc-vscode#85 `remote.extensionKind` is no longer valid.

**ISSUE TYPE**
- Bug Report

**Expected behavior**
```paste below
should be replace with extensionKind
```

**Desktop (please complete the following information):**
 - OS: [**macOS**]
 - Plugin version [**2.1.77**]

**Additional context**
* [vscode-docs](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location)

**Comment by brettmstevens7** [comment]
Thanks @KROSF, this has been updated.
