### ISSUE TITLE
Not Connecting to Open Spotify

### ISSUE THREAD

**Issue by werdna13** [swdotcom/swdc-vscode-musictime#61]
**Describe the bug**
With VS Code is open I try to connect to a Spotify device but it only opens the Spotify app. Then a pop up says "Unable to detect a connected Spotify device. Please make sure you are logged into your account." I have tried both the web version and desktop but neither allow a connection to Spotify. I have premium and I can listen to the music normally. 

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Open VS Code
2. Go to Music time menu
3. Click "Connect to Spotify device"
4. Choice either desktop or web player
5. Get the following error: "Unable to detect a connected Spotify device. Please make sure you are logged into your account."

**Expected behavior**
Click on connect and then be able to see what is playing

**ACTUAL RESULTS**
Just an error promt

**Screenshots**
![image](https://user-images.githubusercontent.com/64917291/111979710-4d1c6e80-8afd-11eb-8497-c08c28f0c655.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Plugin version: Code Time v2.1.
 - VS Code: 1.54.3

**Comment by xavluiz** [comment]
Thank you for the issue update. We'll look into this right away, thanks.

**Comment by xavluiz** [comment]
The latest version, v2.1.24, has updates to transfer to the player, along with efficiencies to prevent rate limiting from Spotify that may cause these types of issues. Would you be able to try that version and let us know if this works for you? If not, would you be able to view the developer tools window found within the Help -> Developer Tools menu, to see if there are any music time errors when you try to connect? Thank you.

**Comment by werdna13** [comment]
Hi I tried the following:

1. Upgraded to 2.1.25 and still had the same issue,
2. I also tried the debugging console, see image below. You can see I had it open whilst I tried to launch both the web and desktop and nothing was logged to the console. There are also no issues raised. 
![image](https://user-images.githubusercontent.com/64917291/112293339-f1cbb700-8c89-11eb-9d28-c3023006d548.png)

**Comment by xavluiz** [comment]
Thank you for the update and console log info. We'll look into reproducing this with the desktop system info you've provided.

**Comment by xavluiz** [comment]
We've found that the flow may try to play the track before checking if the desktop or web player device is available. The patch will not play the track before checking for either the desktop or web player, depending on the selection. I've tested this on windows and its working as expected with v2.1.26. Let me know how this works out for you and I'd be happy to debug this further, thank you.

**Comment by werdna13** [comment]
Hi @xavluiz this seems to be working now for me! Thanks for the support.
