### ISSUE TITLE
Not connecting Spotify account to extension

### ISSUE THREAD

**Issue by adamskrz** [swdotcom/swdc-vscode-musictime#62]
**Describe the bug**
My Spotify account will just not load within the extension. Despite linking my Spotify Premium account with my Code Time account (it shows up in the web dashboard), it will not show up in VS Code (it keeps saying "Connect Spotify") - the Code Time account is logged in and loaded. I have tried on multiple computers with the same result. No matter how many times I follow the link and reauthenticate the account, nothing changes

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Open VS Code
2. Go to Music time menu
3. Press "Connect Spotify"
4. Connect accounts
4. Nothing changes

**Expected behavior**
The account, playlists, and playback controls appear in VS Code, as shown on website

**ACTUAL RESULTS**
Extension still says to connect account

**Screenshots**
![image](https://user-images.githubusercontent.com/35405850/112224584-5ef83180-8c23-11eb-8eb3-50aa0dd68ff5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Music Time 2.1.22, Code Time 2.5.3
 - VS Code 1.54.3

**Comment by xavluiz** [comment]
We're looking into this now, thank you for the issue update and we'll let you know as soon as possible. Thank you.

**Comment by xavluiz** [comment]
We found the issue and have provided a fix in v2.1.23. Please let us know if there's anything else, thank you for your patience.
Regards.

**Comment by OneYellowLemon** [comment]
I am having this issue too, on v2.1.26.
Pressing "Connect Spotify" doesn't connect it after authenticating.

OS: Manjaro 21.1
Code Time 2.5.3
Music Time 2.1.26
VS Code 1.54.3

**Comment by xavluiz** [comment]
Hi, we've been working on a solution for this and should have this out later today. We apologize for the issue and will update this thread when it is available. Thank you.

**Comment by OneYellowLemon** [comment]
The update today (Code Time 2.5.7 and Music Time 2.1.27) has resolved this. Thank you!

**Comment by xavluiz** [comment]
No problem! Sorry I haven’t had a chance to update this channel yet. Let us
know if there are any issues. Regards.

**Comment by adamskrz** [comment]
Seems to be fixed for me as well now! Will close
