### ISSUE TITLE
The only thing that works in the status bar is the heart button

### ISSUE THREAD

**Issue by Oce4nM4n** [swdotcom/swdc-vscode-musictime#64]
**Describe the bug**
Uh the only thing working in the status bar is the heart feature, i can't like pause or play the music.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. sign in
2. launch either web player or desktop app
3. play somthing
4. press the stop button in status bar and nothing happens

**Expected behavior**
It should have paused my music 

**ACTUAL RESULTS**

nothing but after i moved my mouse of it, the icon stayed white as if i was still hovering over it

**Desktop (please complete the following information):**
MacOS
2.1.27

**Additional context**
nothing else

**Comment by mmclead** [comment]
We've updated the entire experience since this version. Please have a look and let us know if you have any issues.
