### ISSUE TITLE
Spotify Playlists not refreshing

### ISSUE THREAD

**Issue by pablovilchis** [swdotcom/swdc-vscode-musictime#65]
**Describe the bug**
```paste below

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Go to 'some Spotify playlist'
2. Double Click on 'some song of the playlist'.
3.  If the song is not in the playlist, the playlist won't play.
4. The playlist are not being refreshed from Spotify

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  macOS Big Sur 11.2.3
 - Plugin version: Code Time v2.5.11, Music Time 2.1.27

**Additional context**
```paste below

```

**Comment by xavluiz** [comment]
Hi @pablovilchis, thank you for the issue update. We'll look into this but just to understand the issue correctly, do you mean that a playlist is not getting updated if you make a change to it outside of the plugin? For example, are you adding to the playlist from within the Spotify desktop? If so, then you are correct, the plugin will not be able to detect this change unless you explicitly refresh it using the refresh button in the upper corner of the tree view. There should also command within the command palette called "Music Time: Reload playlists" that will perform the playlist refresh as well. Thanks.
