### ISSUE TITLE
Adjustable recommendation offset

### ISSUE THREAD

**Issue by chocoelho** [swdotcom/swdc-vscode-musictime#7]
##### SUMMARY

As of now, the recommendation offset is set to 10 songs. It'd be handy to have this value being adjustable by users through some settings variable.

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

Later on, this could be integrated with some sort of ability to add all recommendations into a single playlist.

I think of something like the following:
```json
{
  "swdotcom.musictime.recommendationsOffset": 10
}
```

**Comment by bjacobson26** [comment]
thank you for the feature request. This has been added to our backlog.
