### ISSUE TITLE
the play button does not work when there is advertisement in spotify

### ISSUE THREAD

**Issue by Abhishek12345679** [swdotcom/swdc-vscode-musictime#89]
**Describe the bug**
```paste below
When there is an advertisement and you press the play button in the status bar, it does nothing, you need to do it in manually in the spotify app.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by mmclead** [comment]
@Abhishek12345679 thanks for letting us know.

At that moment, what are you expecting the play button to do?   pause Spotify?  or start playing a different song?

**Comment by Abhishek12345679** [comment]
i expect it to resume the advertisement so that when it ends the next song comes up, at the moment, if spotify is muted on an ad, the play button does nothing.
