### ISSUE TITLE
Continuous Unavailable Favoriting from withing VSCode

### ISSUE THREAD

**Issue by AnishGRao** [swdotcom/swdc-vscode-musictime#9]
**Describe the bug**

Whenever I try to click the hear icon, I recieve "Our service is temporarily unavailable. Please try again later.

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
<!--- Describe exactly how to reproduce the problem -->

On launch of VSCode for windows, and navigating to the Headphones icon, upon clicking the "reconnect" button, and reauthorizing spotify, the extension works as intended. The only missing part is the "favoriting" or heart button from within VSCode. Clicking on this button, leads to a service unavailable message.

**Expected behavior**
A clear and concise description of what you expected to happen.

Favoriting of a song.

```

**ACTUAL RESULTS**

The aforementioned error message.
```

**Desktop (please complete the following information):**
 - OS: W10 Ring 0, with connection to WSL2 Ubuntu Machine 
 - Plugin version: 2.0.1

**Comment by brettmstevens7** [comment]
Hi @AnishGRao, we just pushed an update to make Music Time better and more secure, but will require you to reconnect your Spotify account. Can you try restarting VS Code and reconnecting?

**Comment by AnishGRao** [comment]
Yes, it told me to reconnect my spotify account, and I did so. It still does this though. Does the extension just check for favoriting when making the "AI playlist"? Would it be able to tell from me just favoriting it in the actual spotify app?

**Comment by brettmstevens7** [comment]
Hey @AnishGRao - sorry for the late reply. The AI playlist is based on your listening history while coding using our plugin, and before you have enough data, your liked songs. 

I think you will see this message if there is no running track. I will make a fix.
